# Finite Mappings

We can create linear maps between $\mathbb{R}^N$ and $\mathbb{R}^M$ using the FiniteLinearMapping class found in mappings.py

In [8]:
import sys
sys.path.append('/home/adrian/PhD/BGSOLA/SOLA_DLI/core')
from core.main_classes.mappings import FiniteLinearMapping
from core.main_classes.spaces import RN
import numpy as np

To create such a mapping, we need to provide the domain, codomain, and the matrix representation of the mapping. The domain and codomains here must be spaces. 

In [9]:
A_matrix = np.array([[1,2,3],
              [4,5,6],
              [7,8,10]])
domain = RN(dimension=3)
codomain = RN(dimension=3)

A = FiniteLinearMapping(domain=domain, codomain=codomain, matrix=A_matrix)

We can use this mapping to map elements of the domain to the codomain

In [10]:
v = np.array([1,2,3])
print(A.map(v))

[14 32 53]


We can also invert the operator, which will return another FiniteLinearMapping with the domain and codomain reversed, and the .matrix property inverted. 

In [11]:
A_inverse = A.invert()
print(A_inverse.matrix)

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


If the matrix is almost singular, we cannot directly invert the matrix, so we need to map elements without explicitly inverting the matrix. This is dealt with using the _InverseFiniteLinearMapping class, which uses implicit mapping. 

In [12]:
A_matrix_ill = np.array([[1,2,3],
              [4,5,6],
              [7,8,9.0000000001]])
A = FiniteLinearMapping(domain=domain, codomain=codomain, matrix=A_matrix_ill)
A_inverse = A.invert() # This will throw a warning
print(type(A_inverse)) # The type of this object is _InverseFiniteLinearMapping

print(A_inverse.map(v)) # but we can still map with it (implicitly)

<class 'core.main_classes.mappings._InverseFiniteLinearMapping'>
[-0.33333333  0.66666667 -0.        ]


Linear mappings can also be composed using the "*" operator:

In [13]:
A_mat = np.array([[1,2,1],
              [0,2,1],
              [0,1,3]])

B_mat = np.array([[1,2,1],
              [0,1,1],
              [0,1,3]])
A = FiniteLinearMapping(domain=domain, codomain=codomain, matrix=A_mat)
B = FiniteLinearMapping(domain=domain, codomain=codomain, matrix=B_mat)

C = A*B

print(A.map(B.map(v)))
print(C.map(v))

[29 21 38]
[29 21 38]


We can also obtain the adjoint of our operator:

In [14]:
A_adj = A.adjoint()

print(A_adj.matrix)

[[1 0 0]
 [2 2 1]
 [1 1 3]]


If the operator is ill-conditioned and we need to use the _InverseFiniteLinearMapping, we can still compute the adjoint, and it will also be an istance of _InverseFiniteLinearMapping. Similarly, we can also do composition between a _InverseFiniteLinearMapping and  FiniteLinearMapping. 