# Finite Mappings

We can create linear maps between $\mathbb{R}^N$ and $\mathbb{R}^M$ using the FiniteLinearMapping class found in mappings.py

In [7]:
from sola.main_classes.mappings import FiniteLinearMapping
from sola.main_classes.spaces import RN
import numpy as np

To create such a mapping, we need to provide the domain, codomain, and the matrix representation of the mapping. The domain and codomains here must be spaces. 

In [8]:
A_matrix = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,10]])
domain = RN(dimension=3)
codomain = RN(dimension=3)

A = FiniteLinearMapping(domain=domain,
                        codomain=codomain,
                        matrix=A_matrix)

We can use this mapping to map elements of the domain to the codomain

In [9]:
v = np.array([[1],[2],[3]])
print(A.map(v))

[[14]
 [32]
 [53]]


Invertible mappings can be inverted with the ".invert" method, which will return another FiniteLinearMapping with the domain and codomain reversed, and the .matrix property inverted. 

In [10]:
A_inverse = A.invert()
print(A_inverse.matrix)

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


If a matrix has a very high condition number, instead of a FiniteLinearMapping obejct, the .invert() method will return a ImplicitInvFiniteLinearMapping object which maps elements by solving a system of linear equations. This method is more costly but also more accurate. 

Linear mappings can also be composed using the "*" operator:

In [11]:
A_mat = np.array([[1,2,1],
              [0,2,1],
              [0,1,3]])

B_mat = np.array([[1,2,1],
              [0,1,1],
              [0,1,3]])
A = FiniteLinearMapping(domain=domain,
                        codomain=codomain,
                        matrix=A_mat)
B = FiniteLinearMapping(domain=domain,
                        codomain=codomain,
                        matrix=B_mat)

C = A*B

print(A.map(B.map(v)))
print(C.map(v))

[[29]
 [21]
 [38]]
[[29]
 [21]
 [38]]


We can also obtain the adjoint of our mapping:

In [12]:
A_adj = A.adjoint
print(A_adj)
print(A.matrix)
print(A_adj.matrix)

[[1 2 1]
 [0 2 1]
 [0 1 3]]
[[1 0 0]
 [2 2 1]
 [1 1 3]]


The code only handles square matrices for now. 